### ISSUE TITLE
Can't connect to HTTPS URL because the SSL module is not available.

### ISSUE THREAD

**Issue by saimAbdullah** [mikexstudios/python-firebase#15]
I am having following error appengine 

Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\google_appengine\lib\webapp2-2.5.2\webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "C:\Program Files (x86)\Google\google_appengine\lib\webapp2-2.5.2\webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "C:\Program Files (x86)\Google\google_appengine\lib\webapp2-2.5.2\webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "C:\Program Files (x86)\Google\google_appengine\lib\webapp2-2.5.2\webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "E:\Bolt Reactor\basic app with header\wildpakistan\controllers\Handlers.py", line 26, in dispatch
    webapp2.RequestHandler.dispatch(self)
  File "C:\Program Files (x86)\Google\google_appengine\lib\webapp2-2.5.2\webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "C:\Program Files (x86)\Google\google_appengine\lib\webapp2-2.5.2\webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "E:\Bolt Reactor\basic app with header\wildpakistan\controllers\main.py", line 120, in get
    r = f.push({'user_id': 'wilma', 'text': 'Hello'})
  File "E:\Bolt Reactor\basic app with header\wildpakistan\controllers\main.py", line 45, in push
    return self.post(data)
  File "E:\Bolt Reactor\basic app with header\wildpakistan\controllers\main.py", line 69, in post
    return self.__request('post', data = data)
  File "E:\Bolt Reactor\basic app with header\wildpakistan\controllers\main.py", line 90, in __request
    r = requests.request(method, self.__url(), params=params, **kwargs)
  File "E:\Bolt Reactor\basic app with header\wildpakistan\lib\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Bolt Reactor\basic app with header\wildpakistan\lib\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Bolt Reactor\basic app with header\wildpakistan\lib\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "E:\Bolt Reactor\basic app with header\wildpakistan\lib\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: Can't connect to HTTPS URL because the SSL module is not available.

**Comment by jeffgodwyll** [comment]
See https://cloud.google.com/appengine/docs/python/sockets/ssl_support

You must add the ssl library to your `app.yaml`
```
libraries:
- name: ssl
  version: 2.7
```
